-- CreateTable
CREATE TABLE `heroes` (
    `id` VARCHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `nickname` VARCHAR(255) NOT NULL,
    `date_of_birth` DATETIME NOT NULL,
    `universe` ENUM('MARVEL', 'DC', 'STAR_WARS', 'SENHOR_DOS_ANEIS', 'HARRY_POTTER', 'DRAGON_BALL', 'NARUTO', 'ONE_PIECE', 'BEN_10', 'AVATAR', 'DISNEY', 'TRANSFORMERS', 'THUNDERCATS') NOT NULL,
    `main_power` ENUM('SUPER_FORCA', 'SUPER_VELOCIDADE', 'VOO', 'TELEPATIA', 'TELECINESE', 'MAGIA', 'FATOR_DE_CURA', 'SUPER_INTELIGENCIA', 'AGILIDADE', 'CONTROLE_ELEMENTAL', 'METAMORFOSE', 'INVISIBILIDADE', 'MANIPULACAO_DO_TEMPO', 'PROJECAO_DE_ENERGIA', 'ARTES_MARCIAIS', 'LANCAMENTO_DE_TEIAS', 'VISAO_DE_LASER', 'MAGNETISMO', 'ELASTICIDADE', 'DUPLICACAO', 'TECNOPATIA', 'NECROMANCIA', 'CONTROLE_GRAVITACIONAL', 'DISTORCAO_DA_REALIDADE', 'PODER_COSMICO', 'NINJUTSU', 'GENJUTSU', 'ALQUIMIA') NOT NULL,
    `avatar_url` VARCHAR(500) NOT NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT true,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
